main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('car_list/', views.car_list, name='car_list'),
    path('customer_list/', views.customer_list, name='customer_list'),
    path('walkin_list/', views.walkin_list, name='walkin_list'),
    path('exchange_vehicle/', views.exchange_vehicle, name='exchange_vehicle'),
    path('all_payments/', views.all_payments, name='all_payments'),
    path('all_orders/', views.all_orders, name='all_orders'),
    path('all_delivery/', views.all_delivery, name='all_delivery'),

    path('add_car/', views.add_car, name='add_car'),
    path('add_customer/', views.add_customer, name='add_customer'),
    path('add_walkin/', views.add_walkin, name='add_walkin'),
    path('add_exchange/', views.add_exchange, name='add_exchange'),
    path('add_payments/', views.add_payments, name='add_payments'),
    path('add_orders/', views.add_orders, name='add_orders'),


    path('car/<int:pk>/update', views.CarUpdateView.as_view(), name="car_update"),
    path('customer/<int:pk>/update', views.CustomerUpdateView.as_view(), name="customer_update"),
    path('walkin/<int:pk>/update', views.WalkinUpdateView.as_view(), name="walkin_update"),
    path('exchange_vehicle/<int:pk>/update', views.ExchangeUpdateView.as_view(), name="exchange_update"),
    path('payment/<int:pk>/update', views.PaymentUpdateView.as_view(), name="payment_update"),
    path('order/<int:pk>/update', views.OrderUpdateView.as_view(), name="order_update"),

    path('car/<int:pk>/delete', views.CarDeleteView.as_view(), name="car_delete"),
    path('customer/<int:pk>/delete', views.CustomerDeleteView.as_view(), name="customer_delete"),
    path('walkin/<int:pk>/delete', views.WalkInDeleteView.as_view(), name="walkin_delete"),
    path('exchange_vehicle/<int:pk>/delete', views.ExchangeVehicleDeleteView.as_view(), name="exchange_delete"),
    path('payment/<int:pk>/delete', views.PaymentDeleteView.as_view(), name="payment_delete"),
    path('order/<int:pk>/delete', views.OrderDeleteView.as_view(), name="order_delete"),
    path("order_search/", views.order_search, name="order_search"),   
    path("exchange_search/", views.exchange_search, name="exchange_search"),   
    path("payment_search/", views.payment_search, name="payment_search"),   
    path("walkin_search/", views.walkin_search, name="walkin_search"),   
    path("customer_search/", views.customer_search, name="customer_search"),   






]

seres/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include("main.urls")),
    path("login/", views.login_request, name="login"), #login
    path('signup/',views.signup_request, name='signup'), #signup
    path('profile/<int:pk>', views.profile, name='profile'),
    path("logout/", views.logout_request, name="logout"),



]

    

main/models.py
from django.db import models
from django.core.validators import MinValueValidator


# Create your models here.

class Car(models.Model):
    car_name = models.CharField(max_length=100) 
    car_model = models.CharField(max_length=100, default = 'Full')  

    def __str__(self):
        return f'{self.car_name} - {self.car_model}' 
        
    
class CarColor(models.Model):
    car_color = models.CharField(max_length=100) 
        
    def __str__(self):
        return f'{self.car_color}' 


class Customer(models.Model):
    customer_firstname = models.CharField(max_length=100)
    customer_lastname = models.CharField(max_length=100)
    customer_contact = models.CharField(max_length=100)
    active = models.BooleanField(default=True)


    def __str__(self):
        return f'{self.customer_firstname} {self.customer_lastname}'
    


class WalkIn(models.Model):
    walkin_firstname = models.CharField(max_length=100)
    walkin_lastname = models.CharField(max_length=100)
    walkin_contact = models.CharField(max_length=100)
    purpose_of_visit = models.TextField()
    outcome_of_visit = models.TextField()
    interest_level = models.CharField(max_length=250)
    remarks = models.TextField()
    test_drive = models.BooleanField()
    date_of_walkin = models.DateField()

    def __str__(self):
        return f'{self.walkin_firstname} {self.walkin_lastname}'
    

class BookingType(models.Model):
    booking_type = models.CharField(max_length=100)
   
    def __str__(self):
        return f'{self.booking_type}'

class BookingSource(models.Model):
    booking_source = models.CharField(max_length=100)
   
    def __str__(self):
        return f'{self.booking_source}'



class PaymentType(models.Model):
    payment_type = models.CharField(max_length=100)
   
    def __str__(self):
        return f'{self.payment_type}'

class Payment(models.Model):
    customer = models.ForeignKey('Customer', on_delete=models.CASCADE)
    payment_method = models.ForeignKey('PaymentType', on_delete=models.CASCADE)
    do = models.CharField(max_length=100)
    quotation = models.CharField(max_length=100)
    remarks = models.TextField()

    def __str__(self):
        return f'{self.customer} - {self.payment_method}'
    


class ExchangeVehicle(models.Model):
    customer = models.ForeignKey('Customer', on_delete=models.CASCADE)
    vehicle_name = models.CharField(max_length=250)
    kiloMeters_run = models.IntegerField(default=1)
    vehicle_made_year = models.CharField(max_length=100)
    license_plate = models.CharField(max_length=100, unique='True')
    vehicle_color = models.CharField(max_length=100)
    customer_estimated_value = models.IntegerField(default=1)
    actual_value = models.IntegerField(default=1)
    exchange_status = models.CharField(max_length=150) 

    def __str__(self):
        return f'{self.vehicle_name}'
    
class Orders(models.Model):
    customer = models.ForeignKey('Customer', on_delete=models.CASCADE)
    walkin_customer = models.ForeignKey('WalkIn', on_delete=models.CASCADE, null=True, blank=True)
    payment = models.ForeignKey('PaymentType', on_delete=models.CASCADE)
    car = models.ForeignKey('Car', on_delete=models.CASCADE, null=True) 
    car_color = models.ForeignKey('CarColor', on_delete=models.CASCADE, null=True) 
    booking = models.ForeignKey('BookingType', on_delete=models.CASCADE)
    date_of_order = models.DateField()
    prebooking_amount = models.IntegerField(default=0, validators=[
        MinValueValidator(0)], null=True, blank=True)
    booking_amount = models.IntegerField(default=0, validators=[
        MinValueValidator(0)], null=True, blank=True)
    booking_source = models.ForeignKey('BookingSource', on_delete=models.CASCADE)
    selling_price = models.IntegerField(default=1)
    total_amount_paid = models.IntegerField(default=1)
    remaining_payment= models.IntegerField(default=1)
    remarks = models.TextField(null=True, blank=True)
    cancelled = models.BooleanField()
    reason_of_cancel = models.TextField(null=True, blank=True) 
    delivery = models.BooleanField(null=True, blank=True)
    date_of_delivery = models.DateField(null=True, blank=True)

    def __str__(self):
        return f'{self.customer} - {self.car}'

    def save(self, *args, **kwargs):
        # Deactivate the associated customer
        self.customer.active = False
        self.customer.save()
        super(Orders, self).save(*args, **kwargs)



   

main/forms.py
from django import forms
from .models import *
from django.forms import ModelForm
from django_select2.forms import ModelSelect2Widget


class CarForm(ModelForm):
	class Meta:
			model = Car
			fields = ("car_name", "car_model" )
			labels = {
				'car_name':'Car Name', 
				'car_model':'Car Model', 

			}
			widgets = {
				'car_name': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Car Name'}),
				'car_model': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Car Model'}),

            }
	
class CarColorForm(ModelForm):
	class Meta:
			model = CarColor
			fields = ("car_color",)
			labels = {
				'car_color':'Car Color', 
			}
			widgets = {
				'car_color': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Car Color'}),
            }
	
	
class CustomerForm(ModelForm):
	class Meta:
			model = Customer
			fields = ("customer_firstname", "customer_lastname", 
			"customer_contact")
			labels = {
				'customer_firstname':'First Name', 
				'customer_lastname':'Last Name',
				'customer_contact':'Contact Number', 
			}
			widgets = {
				'customer_firstname': forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name'}),
				'customer_lastname': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name'}),
				'customer_contact': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Contact Number'}),
            }

class WalkInForm(ModelForm):
	class Meta:
			model = WalkIn
			fields = ("walkin_firstname", "walkin_lastname", "walkin_contact", 
			"purpose_of_visit", "outcome_of_visit", "interest_level", "remarks", "test_drive", "date_of_walkin")
			labels = {
				'walkin_firstname':'First Name', 
				'walkin_lastname':'Last Name',
				'walkin_contact':'Contact Number', 
				'purpose_of_visit':'Purpose of Visit', 
                'outcome_of_visit':'Outcome of Visit', 
				'interest_level':'Interest Level ', 
                'remarks':'Remarks', 
                'test_drive':'Test Drive', 
				'date_of_walkin':'Date of WalkIn', 
			}
			widgets = {
				'walkin_firstname': forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name'}),
				'walkin_lastname': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name'}),
				'walkin_contact': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Contact Number'}),
				'purpose_of_visit': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Purpose of Visit '}),
				'outcome_of_visit': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Outcome of Visit '}),
				'interest_level': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Interest Level'}),
				'remarks': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Remarks'}),
				'test_drive': forms.CheckboxInput(attrs={}),
				'date_of_walkin': forms.DateInput(attrs={}),
            }


class ExchangeVehicleForm(ModelForm):
	kiloMeters_run = forms.IntegerField(min_value=1)
	customer_estimated_value = forms.IntegerField(min_value=1)
	actual_value = forms.IntegerField(min_value=1)


	class Meta:
			model = ExchangeVehicle
			fields = ("customer", "vehicle_name", "kiloMeters_run", 
			"vehicle_made_year", "license_plate", "vehicle_color", "customer_estimated_value", "actual_value", "exchange_status")
			labels = {
				'customer':'Customer Name', 
				'vehicle_name':'Vehicle Name',
				'kiloMeters_run':'KiloMeters Run', 
				'vehicle_made_year':'Vehicle Made Year', 
                'license_plate':'License Plate', 
				'vehicle_color':'Vehicle Color ', 
                'customer_estimated_value':'Customer Estimated Value', 
                'actual_value':'Actual Value', 
				'exchange_status':'Exchange Status', 
			}
			widgets = {
				'customer': forms.Select(attrs={}),
				'vehicle_name': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Vehicle Name'}),
				'kiloMeters_run': forms.NumberInput(attrs={'class':'form-control',}),
				'vehicle_made_year': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Vehicle Made Year '}),
				'license_plate': forms.TextInput(attrs={'class':'form-control', 'placeholder':'License Plate '}),
				'vehicle_color': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Vehicle Color'}),
				'customer_estimated_value': forms.NumberInput(attrs={'class':'form-control',}),
				'actual_value': forms.NumberInput(attrs={'class':'form-control',}),
				'exchange_status': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Exchange Status'}),
            }
	
class PaymentForm(ModelForm):
	class Meta:
			model = Payment
			fields = ("customer", "payment_method", "do", "quotation", "remarks")
			labels = {
				'customer':'Customer', 
				'payment_method':'Payment Method',
				'do':'d.o', 
				'quotation':'Quotation',
				'remarks':'Remarks',  
			}
			widgets = {
				'customer': forms.Select(attrs={}),
				'payment_method': forms.Select(attrs={}),
				'do': forms.TextInput(attrs={'class':'form-control', 'placeholder':'d.o'}),
				'quotation': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Quotation'}),
				'remarks': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Remarks'}),
            }
		

class OrdersForm(ModelForm):
	prebooking_amount = forms.IntegerField(min_value=0, required=False)
	booking_amount = forms.IntegerField(min_value=0, required=False)
	selling_price = forms.IntegerField(min_value=0)
	total_amount_paid = forms.IntegerField(min_value=0)
	remaining_payment = forms.IntegerField(min_value=0)

	
	class Meta:
			model = Orders
			fields = ("customer", "walkin_customer", "car", "car_color", "payment", "booking", "prebooking_amount", "booking_amount", "booking_source", "date_of_order", "selling_price", 
			"total_amount_paid", "remaining_payment", "remarks", "cancelled", "reason_of_cancel", "delivery", "date_of_delivery")
			labels = {
				'customer':'Customer', 
				'walkin_customer':'WalkIn Customer',
				'payment':'Payment', 
				'car':'Car',
				'car_color':'Car Color',
				'booking':'Booking Status', 
				'prebooking_amount':'Pre-Booking Amount',
				'booking_amount':'Booking Amount',  
				'booking_source':'Booking Source', 
				'date_of_order':'Date of Order',
				'selling_price':'Selling Price',  
				'total_amount_paid':'Total Amount Paid',  
				'remaining_payment':'Remaining Payment',  
				'remarks':'Remarks',  
				'cancelled':'Cancelled',  
				'reason_of_cancel':'Reason Of Cancel',
				'delivery':'Delivery',
				'date_of_delivery':'Date of Delivery',


			}
			widgets = {
				'customer': forms.Select(attrs={}),
				'walkin_customer': forms.Select(attrs={}),
				'payment': forms.Select(attrs={}),
				'car': forms.Select(attrs={}),
				'car_color': forms.Select(attrs={}),
				'booking': forms.Select(attrs={}),
				'prebooking_amount': forms.NumberInput(attrs={'class':'form-control'}),
				'booking_amount': forms.NumberInput(attrs={'class':'form-control'}),
            	'booking_source': forms.Select(attrs={}),
				'date_of_order': forms.DateInput(attrs={'class':'form-control'}),
				'selling_price': forms.NumberInput(attrs={'class':'form-control'}),
            	'total_amount_paid': forms.NumberInput(attrs={'class':'form-control'}),
            	'remaining_payment': forms.NumberInput(attrs={'class':'form-control'}),
            	'remarks': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Remarks'}),
            	'cancelled': forms.CheckboxInput(attrs={}),
            	'reason_of_cancel': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Reason of Cancel'}),
				'delivery': forms.CheckboxInput(attrs={}),
				'date_of_delivery': forms.DateInput(attrs={'class':'form-control'}),


            }

	def clean(self):
			cleaned_data = super().clean()
			prebooking_amount = cleaned_data.get('prebooking_amount', 0)
			booking_amount = cleaned_data.get('booking_amount', 0)

			# Calculate the total_amount_paid based on prebooking_amount and booking_amount
			total_amount_paid = prebooking_amount + booking_amount
			cleaned_data['total_amount_paid'] = total_amount_paid

			return cleaned_data
	
	def __init__(self, *args, **kwargs):
		super(OrdersForm, self).__init__(*args, **kwargs)
		self.fields['customer'].queryset = Customer.objects.order_by('customer_firstname')
		self.fields['walkin_customer'].queryset = WalkIn.objects.order_by('walkin_firstname')  # Replace 'customer_name' with the field you want to sort by

templates/add_car.html
{% block content %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>SERES</title>
    {% load static %}

    <!-- Link to Bootstrap CSS -->
    
    <link rel="shortcut icon" href="{%static "images/SeresIcon.png" %}">
    <!-- Favicons -->
    <link href="{%static "assets/img/apple-touch-icon.png" %}" rel="apple-touch-icon">
  
    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
  
    <!-- Vendor CSS Files -->
    <link href="{%static "assets/vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{%static "assets/vendor/bootstrap-icons/bootstrap-icons.css" %}" rel="stylesheet">
    <link href="{%static "assets/vendor/boxicons/css/boxicons.min.css" %}" rel="stylesheet">
    <link href="{%static "assets/vendor/quill/quill.snow.css" %}" rel="stylesheet">
    <link href="{%static "assets/vendor/quill/quill.bubble.css" %}" rel="stylesheet">
    <link href="{%static "assets/vendor/remixicon/remixicon.css" %}" rel="stylesheet">
    <link href="{%static "assets/vendor/simple-datatables/style.css" %}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

</head>
<body>
  <main id="main" class="main">
  </br>
    <div class="container text-center"> <!-- Center the content horizontally -->

    <div class="pagetitle">
      <h1>Add Car</h1> 
    </div><!-- End Page Title -->
  </br>

    <section class="section">
        <div class="row justify-content-center"> <!-- Center the content horizontally -->
          <div class="col-lg-6">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Car</h5>

              {% if form %}            
              <form method=POST>
                  {% csrf_token %}
                  {{ form.as_p }} 
                  <button  type="submit" class="btn btn-dark me-2">Add</button>   
                  <a href="{% url 'car_list' %}" class="btn btn-secondary">Cancel</a>

              </form>
              {% endif %}

            </div>
          </div>

        </div>
      </div>
    </section>
  </div>

  </main><!-- End #main -->
{% comment %} 
 <div class="col-md-8 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Add a Car</h4>

        <div class="forms-sample">
            <div class="form-group">
                {% if form %}            
                 <form method=POST>
                     {% csrf_token %}
                     {{ form.as_p }} 
                     <button  type="submit" class="btn btn-dark me-2">Add</button>   
                     <a href="{% url 'car_list' %}" class="btn btn-secondary">Cancel</a>

                 </form>
               
             </div>	
            </div>
        {% endif %} 
      </div>
    </div>
  </div>  {% endcomment %}

 {% block script %}
 <!-- Link to Bootstrap JS and jQuery -->
 <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

  <script src="{%static "assets/vendor/apexcharts/apexcharts.min.js" %}"></script>
  <script src="{%static "assets/vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
  <script src="{%static "assets/vendor/chart.js/chart.umd.js" %}"></script>
  <script src="{%static "assets/vendor/echarts/echarts.min.js" %}"></script>
  <script src="{%static "assets/vendor/quill/quill.min.js" %}"></script>
  <script src="{%static "assets/vendor/simple-datatables/simple-datatables.js" %}"></script>
  <script src="{%static "assets/vendor/tinymce/tinymce.min.js" %}"></script>
  <script src="{%static "assets/vendor/php-email-form/validate.js" %}"></script>

  <!-- Template Main JS File -->
  <script src="{%static "assets/js/main.js" %}"></script>

{% endblock script %} 
</body>
</html>
{% endblock %}

templates/add_orders.html
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>SERES</title>
    {% load static %}

    <!-- Link to Bootstrap CSS -->
   
    <link rel="shortcut icon" href="{%static "images/SeresIcon.png" %}">
    <!-- Favicons -->
    <link href="{%static "assets/img/apple-touch-icon.png" %}" rel="apple-touch-icon">
  
    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
  
    <!-- Vendor CSS Files -->
    <link href="{%static "assets/vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{%static "assets/vendor/bootstrap-icons/bootstrap-icons.css" %}" rel="stylesheet">
    <link href="{%static "assets/vendor/boxicons/css/boxicons.min.css" %}" rel="stylesheet">
    <link href="{%static "assets/vendor/quill/quill.snow.css" %}" rel="stylesheet">
    <link href="{%static "assets/vendor/quill/quill.bubble.css" %}" rel="stylesheet">
    <link href="{%static "assets/vendor/remixicon/remixicon.css" %}" rel="stylesheet">
    <link href="{%static "assets/vendor/simple-datatables/style.css" %}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />

  
  
      
</head>

<body>
    <main id="main" class="main">
    </br>
      <div class="container text-center"> <!-- Center the content horizontally -->
  
      <div class="pagetitle">
        <h1>Add Order</h1> 
      </div><!-- End Page Title -->
    </br>
  
      <section class="section">
          <div class="row justify-content-center"> <!-- Center the content horizontally -->
            <div class="col-lg-6">
  
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Order</h5>
  
                {% if form %}            
                <form method=POST>
                    {% csrf_token %}
                    {{ form.as_p }} 
                    <button  type="submit" class="btn btn-dark me-2">Add</button>   
                    <a href="{% url 'all_orders' %}" class="btn btn-secondary">Cancel</a>
  
                </form>
                {% endif %}
  
              </div>
            </div>
  
          </div>
        </div>
      </section>
    </div>
  
    </main><!-- End #main -->
{% comment %}     
    <div class="container-fluid page-body-wrapper">
        <div class="main-panel">
            <div class="content-wrapper">
                <div class="row">
                    <div class="col-md-6 grid-margin stretch-card">
                        <div class="card my-form">
                            <div class="card-body">
                                <h4 class="card-title">Add Order</h4>
                                <div class="forms-sample">
                                    <div class="form-group">    
                                        {% if form %}            
                                        <form method=POST>
                                        {% csrf_token %}
                                        {{ form.as_p }}    
                                        <button  type="submit" class="btn btn-dark me-2">Add</button>   
                                        <a href="{% url 'all_orders' %}" class="btn btn-secondary">Cancel</a>
                                        </form>
                                        {% endif %} 
                                    </div>
                                </div>
                            </div>	
                        </div>	
                    </div>	
                </div>
            </div>
        </div>
    </div> {% endcomment %}



 {% block script %}
 <!-- Link to Bootstrap JS and jQuery -->
 <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

  <script src="{%static "assets/vendor/apexcharts/apexcharts.min.js" %}"></script>
  <script src="{%static "assets/vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
  <script src="{%static "assets/vendor/chart.js/chart.umd.js" %}"></script>
  <script src="{%static "assets/vendor/echarts/echarts.min.js" %}"></script>
  <script src="{%static "assets/vendor/quill/quill.min.js" %}"></script>
  <script src="{%static "assets/vendor/simple-datatables/simple-datatables.js" %}"></script>
  <script src="{%static "assets/vendor/tinymce/tinymce.min.js" %}"></script>
  <script src="{%static "assets/vendor/php-email-form/validate.js" %}"></script>

  <!-- Template Main JS File -->
  <script src="{%static "assets/js/main.js" %}"></script>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> <!-- Include jQuery library -->

  <script>
    $(document).ready(function () {
        $('#id_prebooking_amount, #id_booking_amount').on('input', function () {
            var prebookingAmount = parseInt($('#id_prebooking_amount').val()) || 0;
            var bookingAmount = parseInt($('#id_booking_amount').val()) || 0;
            var totalAmountPaid = prebookingAmount + bookingAmount;
            $('#id_total_amount_paid').val(totalAmountPaid).prop('readonly', true); // Make the field read-only
        });
    });
    </script>
    
    <script>
        $(document).ready(function () {
            // Function to calculate the remaining_payment
            function calculateRemainingPayment() {
                var sellingPrice = parseInt($('#id_selling_price').val()) || 0;
                var totalAmountPaid = parseInt($('#id_total_amount_paid').val()) || 0;
                var remainingPayment = sellingPrice - totalAmountPaid;
                $('#id_remaining_payment').val(remainingPayment).prop('readonly', true); // Make the field read-only
            }
        
            // Bind input event for prebooking_amount and booking_amount
            $('#id_prebooking_amount, #id_booking_amount').on('input', function () {
                var prebookingAmount = parseInt($('#id_prebooking_amount').val()) || 0;
                var bookingAmount = parseInt($('#id_booking_amount').val()) || 0;
                var totalAmountPaid = prebookingAmount + bookingAmount;
                $('#id_total_amount_paid').val(totalAmountPaid).prop('readonly', true); // Make the field read-only
        
                calculateRemainingPayment();
            });
        
            // Bind input event for selling_price
            $('#id_selling_price').on('input', function () {
                calculateRemainingPayment();
            });
        });
    </script>
  <!-- Activate Select2 for the specified field -->
    <script>
        $(document).ready(function() {
            $('#id_customer').select2();
            $('#id_walkin_customer').select2();        
        });
    </script>
{% endblock script %} 
 
</body>
</html>

{% endblock %}